# SLSA Compliance Policy for MATURING repositories
# Supply-chain Levels for Software Artifacts policy configuration

apiVersion: slsa.dev/v1beta1
kind: Policy
metadata:
  name: fair-credit-scorer-slsa-policy
  version: "1.0.0"
  description: "SLSA Level 3 compliance policy for Fair Credit Scorer"
  labels:
    environment: production
    maturity: maturing
    slsa-level: "3"

spec:
  # Source Requirements for SLSA Level 3
  source:
    level: 3
    requirements:
      versionControl:
        enabled: true
        system: "git"
        provider: "github"
        retentionPolicy: "indefinite"
      
      verifiedHistory:
        enabled: true
        cryptographicIntegrity: true
        tamperEvident: true
      
      twoPersonReview:
        enabled: true
        minimumReviewers: 2
        dismissStaleReviews: true
        requiredApprovals: 2
        restrictPushes: true
      
      signedCommits:
        enabled: true
        required: false  # Will be enabled in future phase
        gpgVerification: true

  # Build Requirements for SLSA Level 3  
  build:
    level: 3
    requirements:
      scriptedBuild:
        enabled: true
        automatedOnly: true
        reproducible: true
      
      buildService:
        enabled: true
        provider: "github-actions"
        managedInfrastructure: true
      
      ephemeralEnvironment:
        enabled: true
        freshEnvironment: true
        noPersistentState: true
        containerBased: true
      
      isolated:
        enabled: true
        networkIsolation: true
        sandboxed: true
        controlledDependencies: true
      
      parameterless:
        enabled: false  # Target for Level 4
        noBuildParameters: false
      
      hermetic:
        enabled: false  # Target for Level 4
        noExternalNetworkAccess: false

  # Provenance Requirements for SLSA Level 3
  provenance:
    level: 3
    requirements:
      available:
        enabled: true
        publiclyAccessible: true
        downloadable: true
      
      authenticated:
        enabled: true
        cryptographicallySigned: true
        certificateTransparency: true
      
      serviceGenerated:
        enabled: true
        trustedService: "github-actions"
        noUserControl: true
      
      nonFalsifiable:
        enabled: true
        isolatedGeneration: true
        tamperEvident: true
        cryptographicallyBound: true
      
      dependenciesComplete:
        enabled: true
        sbomGenerated: true
        transitiveDependencies: true
        lockFiles: true

  # Common Security Requirements
  security:
    level: 3
    requirements:
      buildSecurity:
        enabled: true
        regularUpdates: true
        vulnerabilityScanning: true
        secretManagement: true
      
      accessControl:
        enabled: true
        principleOfLeastPrivilege: true
        multiFactorAuth: true
        auditLogging: true
      
      superuserControls:
        enabled: true
        limitedAccess: true
        approvalWorkflows: true
        regularReviews: true

  # Enforcement Configuration
  enforcement:
    mode: "enforcing"  # Options: permissive, enforcing
    failures:
      action: "block"  # Options: warn, block
      notification:
        enabled: true
        channels:
          - email: "security-team@company.com"
          - slack: "#security-alerts"
          - github: true
    
    exceptions:
      emergencyOverride:
        enabled: true
        requiresApproval: true
        approvers:
          - "security-team"
          - "ciso"
        auditRequired: true
        timeLimit: "24h"

  # Verification Requirements
  verification:
    tools:
      slsaVerifier:
        enabled: true
        version: ">=2.0.0"
        policy: "strict"
      
      cosign:
        enabled: true
        keyless: true
        transparency: true
      
      syft:
        enabled: true
        formats: ["json", "spdx", "cyclonedx"]
      
      grype:
        enabled: true
        failOnSeverity: "high"
        updateDatabase: true

  # Monitoring and Reporting
  monitoring:
    enabled: true
    frequency: "daily"
    metrics:
      complianceScore: true
      policyViolations: true
      riskAssessment: true
    
    reporting:
      monthly: true
      quarterly: true
      annual: true
      recipients:
        - "security-team@company.com"
        - "compliance@company.com"
        - "ciso@company.com"

  # Supply Chain Policies
  supplyChain:
    dependencies:
      allowedSources:
        - "pypi.org"
        - "github.com"
        - "registry.npmjs.org"
      
      blockedPackages:
        - pattern: "*typosquatting*"
          reason: "Potential typosquatting attack"
        - pattern: "*malicious*"
          reason: "Known malicious package"
      
      vulnerabilityThreshold:
        critical: 0
        high: 0
        medium: 5
        low: 20
      
      licensePolicy:
        allowed:
          - "MIT"
          - "Apache-2.0"
          - "BSD-3-Clause"
          - "ISC"
        restricted:
          - "GPL-3.0"
          - "AGPL-3.0"
        prohibited:
          - "WTFPL"
          - "Unlicense"

  # Artifact Policies
  artifacts:
    signing:
      required: true
      algorithm: "ECDSA-P256"
      timestamping: true
    
    attestation:
      required: true
      format: "in-toto"
      predicateType: "https://slsa.dev/provenance/v0.2"
    
    storage:
      retention: "7years"
      integrity: "sha256"
      accessibility: "public"

  # Build Environment Policies  
  buildEnvironment:
    containerImage:
      source: "github-actions"
      scanning: true
      updatePolicy: "weekly"
    
    secrets:
      management: "github-secrets"
      rotation: "quarterly"
      auditAccess: true
    
    isolation:
      networkPolicy: "deny-all"
      fileSystemPolicy: "read-only"
      processPolicy: "sandboxed"

  # Compliance Validation
  validation:
    automated:
      enabled: true
      frequency: "per-build"
      tools:
        - "slsa-verifier"
        - "cosign-verify"
        - "policy-engine"
    
    manual:
      enabled: true
      frequency: "quarterly"
      auditor: "third-party"
    
    continuous:
      enabled: true
      monitoring: "24x7"
      alerting: true

# Policy Exemptions (use sparingly)
exemptions:
  - name: "development-builds"
    scope: "branch:dev/*"
    requirements:
      - "build.isolated.networkIsolation"
    justification: "Development builds need network access for testing"
    expiry: "2024-06-01"
    approver: "security-team"
  
  - name: "emergency-hotfix"
    scope: "tag:hotfix-*"
    requirements:
      - "source.twoPersonReview"
    justification: "Emergency hotfixes may bypass review for critical security issues"
    expiry: "permanent"
    approver: "ciso"

# Custom Rules for ML/AI Projects
customRules:
  fairness:
    modelValidation:
      enabled: true
      biasDetection: true
      fairnessMetrics: true
    
    dataProvenance:
      enabled: true
      sourceTracking: true
      privacyCompliance: true
    
    modelProvenance:
      enabled: true
      trainingProvenance: true
      hyperparameterTracking: true

# Integration Configuration
integrations:
  github:
    webhooks: true
    checkRuns: true
    statusChecks: true
    branchProtection: true
  
  cicd:
    githubActions: true
    workflowValidation: true
    artifactUploads: true
  
  monitoring:
    prometheus: true
    grafana: true
    alertmanager: true
  
  notification:
    slack: true
    email: true
    webhook: true