# Default configuration for fair credit scorer bias mitigation system
# This file contains all configurable parameters with their default values

# Model configuration
model:
  # Logistic regression parameters
  logistic_regression:
    max_iter: 1000
    solver: "liblinear"
  
  # Bias mitigation parameters
  bias_mitigation:
    max_iter: 1000
    solver: "liblinear"
  
  # Default method for evaluation
  default_method: "baseline"

# Data configuration
data:
  # File paths
  default_dataset_path: "data/credit_data.csv"
  
  # Column names
  protected_column_name: "protected"
  label_column_name: "label"
  feature_column_prefix: "feature_"
  
  # Data splitting parameters
  default_test_size: 0.3
  min_test_samples: 1
  stratify_split: true
  
  # CSV output settings
  csv_include_index: false
  
  # Random state for data operations
  random_state: 42
  
  # Synthetic data generation parameters
  synthetic:
    n_samples: 1000
    n_features: 10
    n_informative: 5
    n_redundant: 2
    protected_threshold_method: "mean"

# Evaluation configuration
evaluation:
  # Cross-validation settings
  default_cv_folds: 5
  cv_shuffle: true

# General configuration
general:
  # Random state for reproducibility
  default_random_state: 42

# Fairness configuration
fairness:
  # Post-processing constraint
  postprocess_constraint: "equalized_odds"
  # Prediction method
  predict_method: "predict_proba"

# Output configuration
output:
  # JSON formatting
  json_indent: 2

# Explainability configuration
explainability:
  # Random state for SHAP sampling
  random_state: 42
  # Background sample size for SHAP explainers
  background_sample_size: 50
  # Maximum evaluations for SHAP explainers
  max_evaluations: 100

# Logging configuration
logging:
  # Default logging level
  default_level: "INFO"
  
  # Log format for different handlers
  format:
    # Standard format for most use cases
    standard: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    # Detailed format for debugging
    detailed: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    # Simple format for console output
    simple: "%(levelname)s - %(name)s - %(message)s"
  
  # Date format
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # Handler configuration
  handlers:
    # Console handler settings
    console:
      enabled: true
      level: "INFO"
      format: "simple"
    
    # File handler settings
    file:
      enabled: false  # Disabled by default
      level: "DEBUG"
      format: "detailed"
      filename: "logs/fair_credit_scorer.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
  
  # Module-specific log levels
  modules:
    "src.data_versioning": "INFO"
    "src.performance_benchmarking": "INFO"
    "src.evaluate_fairness": "INFO"
    "src.bias_mitigator": "INFO"
    "src.baseline_model": "INFO"
    "src.fairness_metrics": "INFO"
  
  # Disable specific loggers (useful for third-party libraries)
  disable:
    - "urllib3.connectionpool"
    - "matplotlib.font_manager"