# Performance Monitoring Configuration

monitoring:
  enabled: true
  
  # Performance benchmarks
  benchmarks:
    baseline_model:
      target_accuracy: 0.80
      max_training_time: 30  # seconds
      memory_limit: 500  # MB
    
    fairness_metrics:
      max_computation_time: 5  # seconds
      batch_size: 1000
    
    data_preprocessing:
      max_loading_time: 10  # seconds
      chunk_size: 10000

  # Resource monitoring
  resources:
    cpu_threshold: 80  # percent
    memory_threshold: 85  # percent
    disk_threshold: 90  # percent
    
  # Alerting thresholds
  alerts:
    performance_degradation: 20  # percent slower than baseline
    memory_leak: 50  # MB growth per hour
    error_rate: 5  # percent
    
  # Metrics collection
  metrics:
    enabled: true
    interval: 60  # seconds
    retention: 30  # days
    
    custom_metrics:
      - name: "model_accuracy"
        type: "gauge"
        description: "Current model accuracy"
        
      - name: "bias_metrics"
        type: "histogram"
        description: "Fairness metrics distribution"
        
      - name: "processing_time"
        type: "histogram"
        description: "Data processing time"

  # Health checks
  health_checks:
    endpoint_timeout: 5  # seconds
    check_interval: 30  # seconds
    
    checks:
      - name: "database_connectivity"
        enabled: false  # No database in this project
        
      - name: "model_availability"
        enabled: true
        timeout: 10
        
      - name: "data_integrity"
        enabled: true
        timeout: 15

# OpenTelemetry configuration
telemetry:
  enabled: true
  service_name: "fair-credit-scorer"
  service_version: "0.2.0"
  
  # Exporters
  exporters:
    console:
      enabled: true
      
    jaeger:
      enabled: false
      endpoint: "http://localhost:14268/api/traces"
      
    prometheus:
      enabled: false
      endpoint: "http://localhost:9090"

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  
  structured_logging:
    enabled: true
    include_fields:
      - timestamp
      - level
      - message
      - module
      - function
      - line_number
      - request_id
      
  # Performance logging
  performance_logging:
    enabled: true
    slow_query_threshold: 1000  # milliseconds
    log_sql_queries: false
    
  # Security logging
  security_logging:
    enabled: true
    log_authentication: true
    log_authorization: true
    log_sensitive_operations: true